name: flowpoint
description: A Flutter app for monitoring energy and environmental sensors from ESP32

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  google_fonts: ^6.1.0
  fl_chart: ^1.1.1
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.1.11
  dynamic_color: ^1.3.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.7

flutter:
  uses-material-design: true